using FoodiesGoodies.Api.DTOs.Diet;

namespace FoodiesGoodies.Api.Services.Diet;

public class FallbackDietPlanner : IFallbackDietPlanner
{
    public DietPlanResponse Generate7DayFallbackPlan(DietPlanRequest request, NutritionTargetsDto targets, CuisineContextDto cuisine)
    {
        ArgumentNullException.ThrowIfNull(request);
        ArgumentNullException.ThrowIfNull(targets);
        ArgumentNullException.ThrowIfNull(cuisine);

        int mealCount = Math.Clamp(request.MealCount, 3, 5);
        int targetCals = targets.TargetCalories > 0 ? targets.TargetCalories : 2000;
        string diet = (request.DietPreference ?? "omnivore").ToLowerInvariant();
        string cuisineName = (cuisine.Name ?? "Balanced").ToLowerInvariant();

        var days = new List<DietDayDto>();

        for (int dayNum = 1; dayNum <= 7; dayNum++)
        {
            var dayMeals = GenerateMealsForDay(dayNum, mealCount, targetCals, diet, cuisine, request);
            int dayCal = dayMeals.Sum(m => m.Calories);
            int dayProtein = dayMeals.Sum(m => m.ProteinGrams);
            int dayCarbs = dayMeals.Sum(m => m.CarbsGrams);
            int dayFat = dayMeals.Sum(m => m.FatGrams);

            days.Add(new DietDayDto
            {
                Day = dayNum,
                DayName = $"Day {dayNum}",
                Meals = dayMeals,
                TotalCalories = dayCal,
                TotalProteinGrams = dayProtein,
                TotalCarbsGrams = dayCarbs,
                TotalFatGrams = dayFat
            });
        }

        var groceryList = BuildWeeklyGroceryList(days, cuisine, diet);

        return new DietPlanResponse
        {
            PlanTitle = $"7-Day Personalized {cuisine.Name} Nutrition Plan",
            PlanSource = "FoodiesGoodies Planning Engine",
            Cuisine = cuisine,
            Nutrition = targets,
            Days = days,
            GroceryList = groceryList,
            Recommendations = new List<string>
            {
                $"Daily Calorie Target: ~{targets.TargetCalories} kcal calibrated for {targets.GoalLabel}.",
                $"Hydration: Maintain at least {targets.HydrationLiters} Liters ({targets.HydrationOz} fl oz) of clean water daily.",
                $"Cooking Wisdom: Max cooking time budgeted at {request.MaxCookingTimeMinutes} minutes using authentic {cuisine.Name} spices."
            },
            DigestiveTip = cuisine.DigestiveTradition ?? "Sip warm cumin-fennel infusion after main meals to assist digestion.",
            Disclaimer = "Gemini is temporarily unavailable. Showing a personalized plan generated by the FoodiesGoodies nutrition planning engine.",
            GeneratedAtUtc = DateTime.UtcNow
        };
    }

    public DietMealDto GenerateFallbackSwapMeal(MealSwapRequest request)
    {
        ArgumentNullException.ThrowIfNull(request);

        int cals = request.TargetCalories > 0 ? request.TargetCalories : 500;
        string category = request.MealCategory ?? "Dinner";
        string cuisine = request.Cuisine ?? "Maharashtrian";
        string diet = request.DietPreference ?? "vegetarian";

        return CreateAlternativeMeal(request.Day, category, cals, diet, cuisine, request.MaxCookingTimeMinutes);
    }

    private List<DietMealDto> GenerateMealsForDay(
        int dayNum,
        int mealCount,
        int totalCals,
        string diet,
        CuisineContextDto cuisine,
        DietPlanRequest request)
    {
        var meals = new List<DietMealDto>();
        bool isVeg = diet.Contains("veg");
        bool isVegan = diet.Contains("vegan");
        bool isKeto = diet.Contains("keto");
        string cuisineName = cuisine.Name.ToLowerInvariant();

        // Calorie splits
        int bfastCals, lunchCals, snackCals = 0, snack2Cals = 0, dinnerCals;

        if (mealCount == 3)
        {
            bfastCals = (int)Math.Round(totalCals * 0.28);
            lunchCals = (int)Math.Round(totalCals * 0.38);
            dinnerCals = totalCals - bfastCals - lunchCals;
        }
        else if (mealCount == 5)
        {
            bfastCals = (int)Math.Round(totalCals * 0.22);
            lunchCals = (int)Math.Round(totalCals * 0.30);
            snackCals = (int)Math.Round(totalCals * 0.12);
            snack2Cals = (int)Math.Round(totalCals * 0.10);
            dinnerCals = totalCals - bfastCals - lunchCals - snackCals - snack2Cals;
        }
        else // 4 meals default
        {
            bfastCals = (int)Math.Round(totalCals * 0.25);
            lunchCals = (int)Math.Round(totalCals * 0.35);
            snackCals = (int)Math.Round(totalCals * 0.15);
            dinnerCals = totalCals - bfastCals - lunchCals - snackCals;
        }

        // Breakfast
        meals.Add(CreateMeal(dayNum, "Breakfast", bfastCals, diet, cuisineName, 0, request.MaxCookingTimeMinutes));

        // Lunch
        meals.Add(CreateMeal(dayNum, "Lunch", lunchCals, diet, cuisineName, 1, request.MaxCookingTimeMinutes));

        // Afternoon Snack
        if (mealCount >= 4)
        {
            meals.Add(CreateMeal(dayNum, "Snack", snackCals, diet, cuisineName, 2, Math.Min(15, request.MaxCookingTimeMinutes)));
        }

        // Second Snack for 5-meal schedule
        if (mealCount == 5)
        {
            meals.Add(CreateMeal(dayNum, "Evening Fuel", snack2Cals, diet, cuisineName, 3, Math.Min(15, request.MaxCookingTimeMinutes)));
        }

        // Dinner
        meals.Add(CreateMeal(dayNum, "Dinner", dinnerCals, diet, cuisineName, 4, request.MaxCookingTimeMinutes));

        return meals;
    }

    private DietMealDto CreateMeal(int dayNum, string category, int cals, string diet, string cuisine, int slot, int maxCookingTime)
    {
        int p = (int)Math.Round(cals * 0.28 / 4);
        int c = (int)Math.Round(cals * 0.47 / 4);
        int f = (int)Math.Round(cals * 0.25 / 9);

        // Maharashtrian / North Indian / South Indian / Mediterranean / Japanese / Mexican specific templates
        if (cuisine.Contains("maharashtr"))
        {
            return GetMaharashtrianMeal(dayNum, category, cals, p, c, f, diet, maxCookingTime);
        }
        else if (cuisine.Contains("south indian"))
        {
            return GetSouthIndianMeal(dayNum, category, cals, p, c, f, diet, maxCookingTime);
        }
        else if (cuisine.Contains("north indian") || cuisine.Contains("punjab"))
        {
            return GetNorthIndianMeal(dayNum, category, cals, p, c, f, diet, maxCookingTime);
        }
        else if (cuisine.Contains("japan"))
        {
            return GetJapaneseMeal(dayNum, category, cals, p, c, f, diet, maxCookingTime);
        }
        else if (cuisine.Contains("mediterran") || cuisine.Contains("greek") || cuisine.Contains("ital"))
        {
            return GetMediterraneanMeal(dayNum, category, cals, p, c, f, diet, maxCookingTime);
        }
        else if (cuisine.Contains("mexic"))
        {
            return GetMexicanMeal(dayNum, category, cals, p, c, f, diet, maxCookingTime);
        }

        // Default Balanced
        return GetGlobalMeal(dayNum, category, cals, p, c, f, diet, maxCookingTime);
    }

    private DietMealDto GetMaharashtrianMeal(int day, string cat, int cals, int p, int c, int f, string diet, int cookTime)
    {
        var bfasts = new[]
        {
            ("Kande Pohe with Roasted Peanuts & Lemon", "Flattened rice tempered with mustard seeds, curry leaves, turmeric, and crunchy peanuts, finished with fresh coriander and grated coconut.", new List<string> { "Thick Poha", "Onions", "Peanuts", "Curry Leaves", "Mustard Seeds", "Lemon Juice" }, "Add a squeeze of fresh lime right before serving to boost non-heme iron absorption."),
            ("Sprouted Moong Usal with Multi-Grain Bhakri", "Nutrient-dense whole sprouted moong cooked with goda masala, ginger, and tomatoes, served with warm jowar bhakri.", new List<string> { "Sprouted Moong", "Goda Masala", "Jowar Flour", "Ginger", "Tomatoes" }, "Sprouting triples vitamins C and B-complex while making legumes significantly easier to digest."),
            ("Thalipeeth with Fresh Homemade Dahi", "Savory multi-grain pancake made from roasted bhajan flour (jowar, bajra, chana, wheat) with onions, coriander, and sesame seeds.", new List<string> { "Thalipeeth Bhajan", "Onion", "Sesame Seeds", "Fresh Dahi", "Coriander" }, "Cook on medium flame with a small drop of cold-pressed oil to ensure crispy edges without excess fat."),
            ("Methi Thepla with Low-Fat Curd", "Whole wheat flatbread rolled with fresh fenugreek leaves, ajwain, turmeric, and light curd for soft texture.", new List<string> { "Fresh Methi", "Whole Wheat Atta", "Ajwain", "Turmeric", "Dahi" }, "Fenugreek supports postprandial glycemic control and insulin sensitivity."),
            ("Batata Pohe with Steamed Sprouts", "Light poha prepared with tender potato cubes, tempered curry leaves, and a protein-rich topping of steamed sprouts.", new List<string> { "Poha", "Potatoes", "Mixed Sprouts", "Curry Leaves", "Mustard" }, "Steam sprouts separately to keep them crunchy and preserve heat-sensitive enzymes."),
            ("Upma with Roasted Peanuts & Vegetables", "Roasted semolina tempered with mustard seeds, chana dal, grated ginger, and diced carrots.", new List<string> { "Semolina (Rava)", "Carrots", "Peanuts", "Ginger", "Curry Leaves" }, "Roast the rava until fragrant before adding hot water to avoid lumps."),
            ("Jowar Dosa with Coconut Mint Chutney", "Gluten-free fermented jowar and urad dal crepe cooked golden brown, served with fresh coconut chutney.", new List<string> { "Jowar Flour", "Urad Dal", "Coconut", "Mint", "Green Chillies" }, "Fermenting the batter naturally introduces gut-friendly probiotics.")
        };

        var lunches = new[]
        {
            ("Varan Bhaat with Ghee, Phulka & Methi Sabzi", "Traditional soothing toor dal served over steamed brown or hand-pounded rice with a half teaspoon of cow ghee, accompanied by phulkas and fresh methi.", new List<string> { "Toor Dal", "Brown Rice", "Whole Wheat Atta", "Fresh Methi", "Cow Ghee", "Turmeric" }, "Cow ghee aids assimilation of fat-soluble vitamins (A, D, E, K) present in the greens."),
            ("Pitla with Jowar Bhakri & Thecha", "Classic rustic gram flour stew tempered with garlic and green chillies, paired with warm fiber-rich sorghum bhakri and a mild thecha.", new List<string> { "Besan (Gram Flour)", "Jowar Atta", "Garlic", "Green Chillies", "Curry Leaves" }, "Besan delivers high-quality plant protein and complex carbohydrates with a low glycemic index."),
            ("Matki Chi Usal with Brown Rice & Dal", "Sprouted moth beans simmered in goda masala and tangy kokum gravy, served alongside steamed brown basmati rice.", new List<string> { "Sprouted Matki", "Kokum", "Goda Masala", "Brown Basmati Rice", "Onions" }, "Kokum provides natural hydroxycitric acid, enhancing digestion and gut health."),
            ("Shevga (Drumstick) Curry with Phulkas & Curd", "Mineral-rich fresh drumstick pods stewed in light roasted peanut-onion sauce, paired with warm rotis.", new List<string> { "Drumsticks (Shevga)", "Peanuts", "Tomatoes", "Wheat Phulkas", "Dahi" }, "Drumstick pods and leaves are extraordinarily rich in bioavailable calcium and iron."),
            ("Chavali Chi Usal with Bajra Bhakri", "Black-eyed peas cooked in aromatic Maharashtrian curry with whole pearl millet bhakri and cucumber koshimbir.", new List<string> { "Black-Eyed Peas (Chavali)", "Bajra Atta", "Cucumbers", "Coriander", "Cumin" }, "Bajra is packed with magnesium, supporting healthy muscle recovery and cardiac rhythm."),
            ("Moong Dal Khichdi with Dahi & Roasted Papad", "Comforting one-pot balance of yellow moong dal and rice tempered with cumin, whole black pepper, and turmeric.", new List<string> { "Yellow Moong Dal", "Rice", "Cumin", "Black Pepper", "Cow Ghee", "Dahi" }, "Khichdi provides a complete amino acid profile while remaining gentle on the gastrointestinal tract."),
            ("Katachi Amti with Steamed Rice & Cabbage Sabzi", "Zesty, protein-infused strained chana dal amti tempered with goda masala, served with rice and stir-fried cabbage.", new List<string> { "Chana Dal Extract", "Goda Masala", "Cabbage", "Rice", "Mustard" }, "Amti tempered with mustard and hing stimulates stomach digestive enzymes.")
        };

        var snacks = new[]
        {
            ("Roasted Makhana with Rock Salt & Jeera", "Crunchy fox nuts lightly roasted in cow ghee with cumin powder and Himalayan rock salt.", new List<string> { "Fox Nuts (Makhana)", "Rock Salt", "Cumin Powder", "Cow Ghee" }, "Makhana is a natural low-glycemic, antioxidant-rich snack that curbs evening sweet cravings."),
            ("Sprouted Moong Chaat with Pomegranate", "Steamed sprouted green gram tossed with diced tomatoes, cucumbers, fresh pomegranate arils, and chaat masala.", new List<string> { "Sprouted Moong", "Pomegranate", "Cucumber", "Tomatoes", "Chaat Masala" }, "Pomegranate adds anthocyanins, promoting vascular elasticity."),
            ("Chana Sundal with Fresh Coconut", "Boiled chickpeas tempered with mustard seeds, curry leaves, and grated fresh coconut.", new List<string> { "Chickpeas (Kabuli Chana)", "Mustard Seeds", "Curry Leaves", "Coconut" }, "Chickpeas provide steady slow-burning fuel and high prebiotic soluble fiber."),
            ("Roasted Chana with Jaggery (Gur Chana)", "Dry-roasted Bengal gram paired with a small bite of organic mineral-rich jaggery.", new List<string> { "Roasted Chana", "Organic Jaggery" }, "Classic traditional post-workout snack delivering clean plant iron and protein."),
            ("Fresh Tender Coconut Water & Flesh", "Natural isotonic electrolyte drink with tender coconut jelly.", new List<string> { "Tender Coconut" }, "Restores natural potassium, magnesium, and sodium balance without added sugar."),
            ("Khamang Kakdi (Maharashtrian Cucumber Salad)", "Finely diced cucumbers dressed with crushed roasted peanuts, fresh lemon juice, and green chillies.", new List<string> { "Cucumber", "Crushed Peanuts", "Lemon", "Green Chillies" }, "Cucumbers keep cellular hydration high during the warm afternoon."),
            ("Solkadhi Digestive Drink", "Digestive elixir made with fresh kokum extract, coconut milk, roasted garlic, and cumin.", new List<string> { "Kokum", "Coconut Milk", "Garlic", "Cumin", "Coriander" }, "Solkadhi cools the digestive fire and accelerates metabolic cleansing.")
        };

        var dinners = new[]
        {
            ("Palak Paneer with Multigrain Phulkas", "Fresh paneer simmered in garlic-infused spinach puree with light spices, served with warm multigrain rotis.", new List<string> { "Low-Fat Paneer", "Baby Spinach", "Garlic", "Garam Masala", "Multigrain Atta" }, "Blanch spinach for only 90 seconds and shock in cold water to keep chlorophyll vibrant."),
            ("Methi Pithla with Hot Jowar Bhakri", "Gram flour curry simmered with tender fenugreek greens and garlic, accompanied by hot jowar bhakri.", new List<string> { "Besan", "Fresh Methi", "Garlic", "Jowar Atta", "Turmeric" }, "Methi leaves paired with besan provide high dietary fiber and sustained satiety."),
            ("Sprouted Matki Usal with Phulkas & Salad", "Lightly spiced sprouted moth bean curry with whole wheat phulkas and carrot-beetroot salad.", new List<string> { "Sprouted Matki", "Wheat Phulkas", "Carrots", "Beetroot", "Coriander" }, "A light plant-based dinner ensures deep sleep without digestive distress."),
            ("Tawa Grilled Paneer / Tofu Tikka & Garden Greens", "Cottage cheese or organic tofu cubes marinated in hung curd, kasuri methi, and ajwain, grilled crisp with bell peppers.", new List<string> { "Paneer / Tofu", "Hung Curd", "Bell Peppers", "Kasuri Methi", "Ajwain" }, "High protein before bed supports muscle protein synthesis during overnight sleep."),
            ("Masoor Dal Tadka with Steamed Brown Rice", "Whole brown lentils simmered with onions, tomatoes, and garlic, served with brown rice.", new List<string> { "Brown Masoor Dal", "Tomatoes", "Garlic", "Brown Rice", "Cumin" }, "Whole masoor dal contains intact outer fiber coats that nourish beneficial gut bacteria."),
            ("Bhoplyachi Bhaji (Pumpkin Sabzi) with Phulkas & Dal", "Sweet and savory red pumpkin stir-fry with methi seeds, paired with yellow dal and soft phulkas.", new List<string> { "Red Pumpkin", "Fenugreek Seeds", "Toor Dal", "Wheat Phulkas" }, "Pumpkin is high in beta-carotene, supporting cellular regeneration and eye health."),
            ("Moong Dal & Vegetable Soup with Toasted Multigrain Toast", "Warm, velvety yellow moong dal broth infused with ginger, bottle gourd, and black pepper, served with toasted sourdough.", new List<string> { "Yellow Moong Dal", "Bottle Gourd", "Ginger", "Black Pepper", "Multigrain Bread" }, "Gentle on the stomach, ideal for restorative weekend recovery.")
        };

        int idx = (day - 1) % 7;
        (string name, string desc, List<string> ings, string tip) tuple;

        if (cat.Contains("Breakfast")) tuple = bfasts[idx];
        else if (cat.Contains("Lunch")) tuple = lunches[idx];
        else if (cat.Contains("Snack") || cat.Contains("Fuel")) tuple = snacks[idx];
        else tuple = dinners[idx];

        return new DietMealDto
        {
            MealId = $"day-{day}-{cat.ToLowerInvariant().Replace(" ", "-")}",
            Category = cat,
            Name = tuple.name,
            Description = tuple.desc,
            Ingredients = tuple.ings,
            Calories = cals,
            ProteinGrams = p,
            CarbsGrams = c,
            FatGrams = f,
            ChefTip = tuple.tip,
            CookingTimeMinutes = Math.Min(cookTime, 30)
        };
    }

    private DietMealDto GetSouthIndianMeal(int day, string cat, int cals, int p, int c, int f, string diet, int cookTime)
    {
        string name = $"{cat} - Authentic South Indian Option {day}";
        string desc = "Nutritious South Indian preparation with traditional fermented grains and spices.";
        var ings = new List<string> { "Urad Dal", "Rice", "Sambar Dal", "Curry Leaves", "Mustard Seeds" };
        string tip = "Use cold-pressed sesame oil (gingelly) for authentic flavor and polyphenols.";

        if (cat.Contains("Breakfast"))
        {
            name = day % 2 == 1 ? "Steamed Ragi Idlis with Drumstick Sambar" : "Crispy Pesarattu (Green Gram Dosa) with Ginger Chutney";
            desc = "Fermented, highly digestible breakfast rich in fiber, calcium, and plant protein.";
            ings = new List<string> { "Ragi Flour", "Urad Dal", "Drumsticks", "Toor Dal", "Curry Leaves", "Mustard" };
            tip = "Pesarattu made from whole moong requires zero fermentation and provides sustained morning energy.";
        }
        else if (cat.Contains("Lunch"))
        {
            name = day % 2 == 1 ? "South Indian Thali: Rice, Dal Sambar, Beetroot Poriyal & Curd" : "Lemon Rice with Roasted Peanuts & Vegetable Avial";
            desc = "Balanced traditional midday meal featuring fiber-rich vegetable poriyal and probiotic curd.";
            ings = new List<string> { "Parboiled Rice", "Toor Dal", "Beetroot", "Curd", "Curry Leaves", "Coconut" };
            tip = "Poriyal cooked with minimal coconut and dry roasting keeps calories balanced.";
        }
        else if (cat.Contains("Snack"))
        {
            name = "Boiled Kala Chana Sundal with Grated Coconut";
            desc = "Wholesome black chickpeas tossed with mustard seeds, curry leaves, and a sprinkle of coconut.";
            ings = new List<string> { "Black Chickpeas", "Mustard", "Curry Leaves", "Coconut", "Green Chillies" };
            tip = "Black chickpeas are extraordinarily rich in insoluble fiber, regulating blood sugar levels.";
        }
        else
        {
            name = day % 2 == 1 ? "Vegetable Rasam with Steamed Rice & Grilled Low-Fat Paneer" : "Ragi Mudde with Mixed Lentil Saaru & Cucumber Slices";
            desc = "Light, restorative evening meal with anti-inflammatory medicinal rasam spices.";
            ings = new List<string> { "Ragi", "Tomatoes", "Black Pepper", "Cumin", "Garlic", "Paneer" };
            tip = "Fresh black pepper rasam stimulates peristalsis and soothes the respiratory tract.";
        }

        return new DietMealDto
        {
            MealId = $"day-{day}-{cat.ToLowerInvariant().Replace(" ", "-")}",
            Category = cat,
            Name = name,
            Description = desc,
            Ingredients = ings,
            Calories = cals,
            ProteinGrams = p,
            CarbsGrams = c,
            FatGrams = f,
            ChefTip = tip,
            CookingTimeMinutes = Math.Min(cookTime, 30)
        };
    }

    private DietMealDto GetNorthIndianMeal(int day, string cat, int cals, int p, int c, int f, string diet, int cookTime)
    {
        string name = $"{cat} - Wholesome North Indian Plate {day}";
        string desc = "Rich, flavorful North Indian nutrition calibrated for balanced energy and satiety.";
        var ings = new List<string> { "Whole Wheat Atta", "Lentils", "Spices", "Tomatoes" };
        string tip = "Use dry roasting and kasuri methi for rich aroma with minimal cooking oil.";

        if (cat.Contains("Breakfast"))
        {
            name = day % 2 == 1 ? "Sprouted Moong & Paneer Chilla with Mint Chutney" : "Stuffed Methi Phulkas with Homemade Low-Fat Dahi";
            desc = "High-protein savory crepes packed with paneer, ginger, and aromatic fresh herbs.";
            ings = new List<string> { "Moong Dal", "Paneer", "Ginger", "Mint", "Green Chillies" };
            tip = "Cook chillas on a well-seasoned cast iron skillet for optimal heat retention.";
        }
        else if (cat.Contains("Lunch"))
        {
            name = day % 2 == 1 ? "Yellow Dal Tadka, Seasonal Bhindi & Warm Phulkas" : "Amritsari Rajma Masala with Steamed Brown Basmati Rice";
            desc = "Hearty, comforting legumes stewed with ripe tomatoes, ginger, and cumin, served with whole grains.";
            ings = new List<string> { "Kidney Beans (Rajma)", "Brown Rice", "Tomatoes", "Ginger", "Garam Masala" };
            tip = "Slow simmer kidney beans with a pinch of black cardamom to develop deep culinary depth.";
        }
        else if (cat.Contains("Snack"))
        {
            name = "Roasted Makhana with Rock Salt & Green Tea";
            desc = "Fox nuts gently roasted with cumin and pink salt, accompanied by antioxidant-rich green tea.";
            ings = new List<string> { "Fox Nuts", "Rock Salt", "Cumin", "Green Tea" };
            tip = "Makhana is rich in kaempferol, a natural flavonoid with potent anti-aging properties.";
        }
        else
        {
            name = day % 2 == 1 ? "Palak Paneer with Multigrain Phulkas & Salad" : "Yellow Moong Dal Khichdi with Dahi & Roasted Jeera";
            desc = "Fresh artisanal paneer folded into garlic-tempered spinach puree, paired with multigrain rotis.";
            ings = new List<string> { "Paneer", "Spinach", "Garlic", "Whole Wheat", "Dahi" };
            tip = "Spinach and paneer provide a synergistic balance of magnesium and complete dairy protein.";
        }

        return new DietMealDto
        {
            MealId = $"day-{day}-{cat.ToLowerInvariant().Replace(" ", "-")}",
            Category = cat,
            Name = name,
            Description = desc,
            Ingredients = ings,
            Calories = cals,
            ProteinGrams = p,
            CarbsGrams = c,
            FatGrams = f,
            ChefTip = tip,
            CookingTimeMinutes = Math.Min(cookTime, 30)
        };
    }

    private DietMealDto GetJapaneseMeal(int day, string cat, int cals, int p, int c, int f, string diet, int cookTime)
    {
        string name = $"{cat} - Japanese Washoku {day}";
        string desc = "Harmonious Japanese meal honoring fresh sea ingredients, fermented miso, and steamed grains.";
        var ings = new List<string> { "Miso", "Rice", "Tofu", "Seaweed", "Sesame" };
        string tip = "Never boil miso broth vigorously; dissolve paste into warm dashi to preserve live probiotics.";

        if (cat.Contains("Breakfast"))
        {
            name = "Traditional Asagohan: Steamed Salmon, Wakame Miso Soup & Rice";
            desc = "Clean morning balance of grilled wild salmon, probiotic miso broth, and steamed rice.";
            ings = new List<string> { "Wild Salmon", "Miso Paste", "Wakame Seaweed", "Brown Rice", "Scallions" };
            tip = "Wakame provides natural iodine, essential for healthy thyroid hormone synthesis.";
        }
        else if (cat.Contains("Lunch"))
        {
            name = "Buckwheat Soba Noodle Bowl with Edamame & Steamed Greens";
            desc = "Nutty buckwheat soba noodles served in light dashi broth with shelled edamame and bok choy.";
            ings = new List<string> { "Buckwheat Soba", "Edamame", "Bok Choy", "Shiitake Dashi", "Nori" };
            tip = "Buckwheat is naturally gluten-free and packed with rutin, a bioflavonoid that protects capillaries.";
        }
        else if (cat.Contains("Snack"))
        {
            name = "Steamed Sea Salt Edamame & Roasted Genmaicha Tea";
            desc = "Warm whole edamame pods tossed with coarse sea salt, paired with brown rice green tea.";
            ings = new List<string> { "Edamame Pods", "Sea Salt", "Genmaicha Tea" };
            tip = "Edamame delivers all nine essential amino acids alongside healthy plant isoflavones.";
        }
        else
        {
            name = "Miso-Glazed Tofu / Black Cod with Steamed Brown Rice & Kinpira Gobo";
            desc = "Savory glazed protein baked golden brown, served with steamed rice and braised carrots.";
            ings = new List<string> { "Firm Tofu", "Miso Paste", "Mirin touch", "Brown Rice", "Carrots", "Sesame" };
            tip = "Garnish with toasted white sesame seeds for bioavailable calcium and nutty aroma.";
        }

        return new DietMealDto
        {
            MealId = $"day-{day}-{cat.ToLowerInvariant().Replace(" ", "-")}",
            Category = cat,
            Name = name,
            Description = desc,
            Ingredients = ings,
            Calories = cals,
            ProteinGrams = p,
            CarbsGrams = c,
            FatGrams = f,
            ChefTip = tip,
            CookingTimeMinutes = Math.Min(cookTime, 30)
        };
    }

    private DietMealDto GetMediterraneanMeal(int day, string cat, int cals, int p, int c, int f, string diet, int cookTime)
    {
        string name = $"{cat} - Mediterranean Blue Zone {day}";
        string desc = "Heart-healthy Mediterranean meal with cold-pressed olive oil, herbs, and legumes.";
        var ings = new List<string> { "Olive Oil", "Chickpeas", "Tomatoes", "Oregano", "Feta" };
        string tip = "Use cold-pressed extra virgin olive oil as a finishing drizzle over cooked vegetables.";

        if (cat.Contains("Breakfast"))
        {
            name = "Greek Scrambled Eggs with Feta, Tomatoes & Sourdough";
            desc = "Farm-fresh eggs gently scrambled with diced vine-ripened tomatoes, sheep feta, and oregano.";
            ings = new List<string> { "Eggs", "Feta Cheese", "Vine Tomatoes", "Sourdough Bread", "Extra Virgin Olive Oil" };
            tip = "Cook eggs over low heat to keep curds velvety and preserve delicate fatty acids.";
        }
        else if (cat.Contains("Lunch"))
        {
            name = "Mediterranean Chickpea & Farro Salad with Kalamata Olives";
            desc = "Ancient farro grains tossed with chickpeas, cucumbers, cherry tomatoes, and lemon-oregano vinaigrette.";
            ings = new List<string> { "Farro", "Chickpeas", "Kalamata Olives", "Cucumbers", "Oregano", "Lemon" };
            tip = "Farro offers a satisfying chewy texture and two times more fiber than standard modern wheat.";
        }
        else if (cat.Contains("Snack"))
        {
            name = "Greek Yogurt with Raw Honey, Walnuts & Berries";
            desc = "Thick strained Greek yogurt drizzled with wild mountain honey and crushed walnut halves.";
            ings = new List<string> { "Greek Yogurt", "Raw Honey", "Walnuts", "Wild Blueberries" };
            tip = "Walnuts are the premier plant source of alpha-linolenic acid (omega-3 ALA).";
        }
        else
        {
            name = "Herb-Baked Salmon or Lentil Stew with Braised Greens";
            desc = "Wild salmon or brown lentils stewed with rosemary, garlic, and extra virgin olive oil with dark greens.";
            ings = new List<string> { "Wild Salmon / Brown Lentils", "Garlic", "Rosemary", "Swiss Chard", "Olive Oil" };
            tip = "A squeeze of fresh lemon over greens enhances non-heme iron absorption significantly.";
        }

        return new DietMealDto
        {
            MealId = $"day-{day}-{cat.ToLowerInvariant().Replace(" ", "-")}",
            Category = cat,
            Name = name,
            Description = desc,
            Ingredients = ings,
            Calories = cals,
            ProteinGrams = p,
            CarbsGrams = c,
            FatGrams = f,
            ChefTip = tip,
            CookingTimeMinutes = Math.Min(cookTime, 30)
        };
    }

    private DietMealDto GetMexicanMeal(int day, string cat, int cals, int p, int c, int f, string diet, int cookTime)
    {
        string name = $"{cat} - Traditional Mexican Plate {day}";
        string desc = "Wholesome traditional Mexican nutrition emphasizing heirloom corn, black beans, and fresh avocado.";
        var ings = new List<string> { "Corn Tortillas", "Black Beans", "Avocado", "Salsa Verde", "Cilantro" };
        string tip = "Lime juice and fresh cilantro elevate flavor while contributing bioflavonoids.";

        if (cat.Contains("Breakfast"))
        {
            name = "Huevos a la Mexicana with Warm Corn Tortillas & Black Beans";
            desc = "Eggs scrambled with diced tomatoes, onions, and jalapeños, served with warm corn tortillas and simmered black beans.";
            ings = new List<string> { "Eggs", "Corn Tortillas", "Black Beans", "Tomatoes", "Jalapeño", "Cilantro" };
            tip = "Corn tortillas combined with black beans form a complete essential amino acid profile.";
        }
        else if (cat.Contains("Lunch"))
        {
            name = "Black Bean & Grilled Chicken / Tofu Burrito Bowl with Salsa Verde";
            desc = "Brown rice bowl loaded with seasoned black beans, grilled protein, avocado slices, and tangy tomatillo salsa.";
            ings = new List<string> { "Black Beans", "Grilled Chicken / Tofu", "Brown Rice", "Avocado", "Tomatillos", "Lime" };
            tip = "Tomatillos in salsa verde are rich in vitamin C and natural dietary fiber.";
        }
        else if (cat.Contains("Snack"))
        {
            name = "Fresh Jicama & Cucumber Slices with Tajín & Lime";
            desc = "Crisp mineral-rich jicama sticks tossed with fresh lime juice and chili-lime seasoning.";
            ings = new List<string> { "Jicama", "Cucumbers", "Lime Juice", "Chili Seasoning" };
            tip = "Jicama is packed with inulin, a potent prebiotic that feeds beneficial Bifidobacteria.";
        }
        else
        {
            name = "Baked Enchiladas Verdes with Avocado Salad & Pinto Beans";
            desc = "Corn tortillas rolled with shredded protein, baked under mild green salsa, served with pinto beans.";
            ings = new List<string> { "Corn Tortillas", "Salsa Verde", "Pinto Beans", "Avocado", "Cilantro", "Cotija" };
            tip = "Bake with light cotija cheese for rich saltiness without overwhelming saturated fat.";
        }

        return new DietMealDto
        {
            MealId = $"day-{day}-{cat.ToLowerInvariant().Replace(" ", "-")}",
            Category = cat,
            Name = name,
            Description = desc,
            Ingredients = ings,
            Calories = cals,
            ProteinGrams = p,
            CarbsGrams = c,
            FatGrams = f,
            ChefTip = tip,
            CookingTimeMinutes = Math.Min(cookTime, 30)
        };
    }

    private DietMealDto GetGlobalMeal(int day, string cat, int cals, int p, int c, int f, string diet, int cookTime)
    {
        string name = $"{cat} - Global Clean Nutrition Plate {day}";
        string desc = "Balanced whole-food preparation designed for metabolic health and sustained daily vitality.";
        var ings = new List<string> { "Quinoa", "Greens", "Lean Protein", "Olive Oil", "Herbs" };
        string tip = "Prioritize colorful vegetables to obtain a wide spectrum of phytonutrients.";

        if (cat.Contains("Breakfast"))
        {
            name = "Overnight Oats with Chia Seeds, Greek Yogurt & Berries";
            desc = "Rolled oats soaked in almond milk with chia seeds, wild berries, and a scoop of Greek yogurt.";
            ings = new List<string> { "Rolled Oats", "Chia Seeds", "Greek Yogurt", "Berries", "Almond Milk" };
            tip = "Chia seeds form a soluble fiber gel that slows carbohydrate absorption.";
        }
        else if (cat.Contains("Lunch"))
        {
            name = "Tri-Color Quinoa & Roasted Vegetable Power Bowl";
            desc = "Fluffy quinoa topped with roasted bell peppers, zucchini, chickpeas, and lemon-tahini dressing.";
            ings = new List<string> { "Quinoa", "Chickpeas", "Zucchini", "Bell Peppers", "Tahini", "Lemon" };
            tip = "Quinoa is one of the few plant grains that naturally contains all nine essential amino acids.";
        }
        else if (cat.Contains("Snack"))
        {
            name = "Crisp Apple Slices with Raw Almond Butter";
            desc = "Organic apple wedges paired with pure stone-ground almond butter and cinnamon.";
            ings = new List<string> { "Apple", "Almond Butter", "Ceylon Cinnamon" };
            tip = "Combining fruit with healthy nut fats prevents postprandial glucose spikes.";
        }
        else
        {
            name = "Herb-Grilled Salmon or Spiced Lentil Curry with Steamed Greens";
            desc = "Lean protein served with steamed broccoli, roasted sweet potatoes, and cold-pressed olive oil.";
            ings = new List<string> { "Salmon / Lentils", "Sweet Potatoes", "Broccoli", "Olive Oil", "Garlic" };
            tip = "Steam broccoli for 4 minutes to maximize active sulforaphane bioavailability.";
        }

        return new DietMealDto
        {
            MealId = $"day-{day}-{cat.ToLowerInvariant().Replace(" ", "-")}",
            Category = cat,
            Name = name,
            Description = desc,
            Ingredients = ings,
            Calories = cals,
            ProteinGrams = p,
            CarbsGrams = c,
            FatGrams = f,
            ChefTip = tip,
            CookingTimeMinutes = Math.Min(cookTime, 30)
        };
    }

    private DietMealDto CreateAlternativeMeal(int day, string cat, int cals, string diet, string cuisine, int cookTime)
    {
        int p = (int)Math.Round(cals * 0.28 / 4);
        int c = (int)Math.Round(cals * 0.47 / 4);
        int f = (int)Math.Round(cals * 0.25 / 9);

        return new DietMealDto
        {
            MealId = $"day-{day}-{cat.ToLowerInvariant()}-swapped-{Guid.NewGuid().ToString("N")[..6]}",
            Category = cat,
            Name = $"Chef's Alternative: Sprouted Moong & Paneer Salad with Roasted Cumin",
            Description = $"A freshly swapped, balanced {cuisine} alternative formulated to match your exact {cals} kcal macro target.",
            Ingredients = new List<string> { "Sprouted Moong", "Low-Fat Paneer", "Cucumbers", "Tomatoes", "Roasted Cumin", "Lemon Juice" },
            Calories = cals,
            ProteinGrams = p,
            CarbsGrams = c,
            FatGrams = f,
            ChefTip = "Seasoned with Himalayan rock salt and roasted jeera for light, effortless assimilation.",
            CookingTimeMinutes = Math.Min(cookTime, 20)
        };
    }

    private List<GroceryCategoryDto> BuildWeeklyGroceryList(List<DietDayDto> days, CuisineContextDto cuisine, string diet)
    {
        var produceSet = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        var grainsSet = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        var proteinSet = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        var spicesSet = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        var otherSet = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        foreach (var day in days)
        {
            foreach (var meal in day.Meals)
            {
                foreach (var ing in meal.Ingredients)
                {
                    string item = ing.Trim();
                    string lower = item.ToLowerInvariant();

                    if (lower.Contains("spinach") || lower.Contains("palak") || lower.Contains("methi") ||
                        lower.Contains("tomato") || lower.Contains("onion") || lower.Contains("cucumber") ||
                        lower.Contains("carrot") || lower.Contains("lemon") || lower.Contains("cilantro") ||
                        lower.Contains("ginger") || lower.Contains("garlic") || lower.Contains("apple") ||
                        lower.Contains("berry") || lower.Contains("pomegranate") || lower.Contains("avocado") ||
                        lower.Contains("zucchini") || lower.Contains("bok choy") || lower.Contains("gourd") ||
                        lower.Contains("pumpkin") || lower.Contains("drumstick"))
                    {
                        produceSet.Add(item);
                    }
                    else if (lower.Contains("rice") || lower.Contains("poha") || lower.Contains("jowar") ||
                             lower.Contains("bajra") || lower.Contains("atta") || lower.Contains("wheat") ||
                             lower.Contains("oats") || lower.Contains("quinoa") || lower.Contains("bread") ||
                             lower.Contains("soba") || lower.Contains("farro") || lower.Contains("tortilla"))
                    {
                        grainsSet.Add(item);
                    }
                    else if (lower.Contains("paneer") || lower.Contains("tofu") || lower.Contains("salmon") ||
                             lower.Contains("chicken") || lower.Contains("egg") || lower.Contains("dal") ||
                             lower.Contains("moong") || lower.Contains("chana") || lower.Contains("matki") ||
                             lower.Contains("rajma") || lower.Contains("lentil") || lower.Contains("edamame") ||
                             lower.Contains("curd") || lower.Contains("dahi") || lower.Contains("yogurt") ||
                             lower.Contains("feta") || lower.Contains("makhana"))
                    {
                        proteinSet.Add(item);
                    }
                    else if (lower.Contains("masala") || lower.Contains("cumin") || lower.Contains("mustard") ||
                             lower.Contains("turmeric") || lower.Contains("ghee") || lower.Contains("oil") ||
                             lower.Contains("kokum") || lower.Contains("pepper") || lower.Contains("salt") ||
                             lower.Contains("miso") || lower.Contains("oregano") || lower.Contains("tahini"))
                    {
                        spicesSet.Add(item);
                    }
                    else
                    {
                        otherSet.Add(item);
                    }
                }
            }
        }

        return new List<GroceryCategoryDto>
        {
            new GroceryCategoryDto { Category = "Fresh Produce & Herbs", Items = produceSet.Take(12).ToList() },
            new GroceryCategoryDto { Category = "Whole Grains & Staples", Items = grainsSet.Take(8).ToList() },
            new GroceryCategoryDto { Category = "Proteins, Legumes & Dairy", Items = proteinSet.Take(10).ToList() },
            new GroceryCategoryDto { Category = "Traditional Spices & Oils", Items = spicesSet.Take(8).ToList() },
            new GroceryCategoryDto { Category = "Pantry Essentials", Items = otherSet.Take(6).ToList() }
        };
    }
}
